---
abstract: 'Automatically include GitHub meta information in META.yml'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
  - 'Ricardo SIGNES <rjbs@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-GithubMeta
requires:
  Dist::Zilla: 4.101582
  Dist::Zilla::Role::MetaProvider: 4.101582
  IPC::Cmd: 0.58
  Moose: 1.07
  MooseX::Types::URI: 0.02
  perl: 5.008005
resources:
  homepage: https://github.com/bingos/dist-zilla-plugin-githubmeta
  repository: https://github.com/bingos/dist-zilla-plugin-githubmeta.git
version: 0.22
